version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install zip -y
  build:
    commands:
      - echo "Zipping deployment package...".
      - zip -g build.zip index.js
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws --version
      - aws configure set region us-east-2
      - aws lambda update-function-code --function-name http-crud-fun --zip-file fileb://build.zip
      - echo "DONE!!"
